parameters:
    getonlyimg.menu_builder.class: Application\Bundle\Menu\MenuBuilder

services:
    getonlyimg_main.menu_builder:
        class: %getonlyimg.menu_builder.class%
        arguments: ["@knp_menu.factory"]

    getonlyimg_main.menu.main:
        class: "Knp\Menu\MenuItem" # the service definition requires setting the class
        factory_service: getonlyimg_main.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main }
